### ISSUE TITLE
Error voting

### ISSUE THREAD

**Issue by dworthen** [gov4git/gov4git#124]
**Describe the bug**
Running `gov4git ballot vote --name github/issues/20 --choices prioritize --strengths 625` results in a stderr `file does not exist`

This is for the plurality repo and specifically this ballot: https://github.com/pluralitybook/plurality-gov.public/blob/main/ballot/github/issues/20/ballot_ad.json

Though I am getting the error for all ballots in the plurality project. The ballot appears to be open. I tested from both windows and linux and got the error using the v1.1.13 cli. 

Here is the full stack trace when running with `-v`

```bash
g4g ballot vote --name github/issues/20 --choices prioritize --strengths 625 --config C:\Users\derek\.gov4git\8ea6982c37c79c338efe64eebe9bbfdcddc6dd58911d58be65ba046853ca23e5.json -v
node:internal/errors:867
  const err = new Error(message);
              ^

Error: Command failed: C:\Users\derek\AppData\Roaming\npm\node_modules\@gov4git\js-client\bin\gov4git.exe ballot vote --name github/issues/20 --choices prioritize --strengths 625 --config C:\Users\derek\.gov4git\8ea6982c37c79c338efe64eebe9bbfdcddc6dd58911d58be65ba046853ca23e5.json -v
2023-10-31T13:20:20.611-0700    INFO    base/logging.go:61      /home/runner/work/gov4git/gov4git/gov4git/cmd/root.go:65 gov4git version: dev-rev-8cc3a18-2023-10-25
goroutine 1 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.21.3/x64/src/runtime/debug/stack.go:24 +0x5e
github.com/gov4git/lib4git/must.mkErr(...)
        /home/runner/go/pkg/mod/github.com/gov4git/lib4git@v0.0.27/must/must.go:16
github.com/gov4git/lib4git/must.Panic(...)
        /home/runner/go/pkg/mod/github.com/gov4git/lib4git@v0.0.27/must/must.go:20
github.com/gov4git/lib4git/form.FromFile[...]({0x177a188?, 0xc0001bcc60}, {0x177e4f0, 0xc00007c460?}, {0xc0006800f0?, 0xffffffff37363534?})
        /home/runner/go/pkg/mod/github.com/gov4git/lib4git@v0.0.27/form/form.go:98 +0x65
github.com/gov4git/gov4git/proto/kv.KV[...].ListKeys(0x1780d20, {0x177a188, 0xc0001bcc60}, {0xc000119d40, 0x2, 0x2}, 0xc0002bc7b0)
        /home/runner/work/gov4git/gov4git/proto/kv/kv.go:72 +0x232
github.com/gov4git/gov4git/proto/member.LookupUserByID_Local({0x177a188, 0xc0001bcc60}, 0xc0002bc600?, {0xc0004cf880, 0x34})
        /home/runner/work/gov4git/gov4git/proto/member/user.go:138 +0x72
github.com/gov4git/gov4git/proto/ballot/qv.QV.VerifyElections({}, {0x177a188, 0xc0001bcc60}, {{{0xc00001e340, 0x37}, {0xc00000a684, 0x4}}, {{0xc00001e380, 0x38}, {0xc00000a688, ...}}}, ...)
        /home/runner/work/gov4git/gov4git/proto/ballot/qv/verify.go:26 +0x111
github.com/gov4git/gov4git/proto/ballot/ballot.verifyElections({_, _}, {_, _}, {{{0xc00001e340, 0x37}, {0xc00000a684, 0x4}}, {{0xc00001e380, 0x38}, ...}}, ...)
        /home/runner/work/gov4git/gov4git/proto/ballot/ballot/vote.go:108 +0x294
github.com/gov4git/gov4git/proto/ballot/ballot.Vote_StageOnly({_, _}, {{{0xc00001e340, 0x37}, {0xc00000a684, 0x4}}, {{0xc00001e380, 0x38}, {0xc00000a688, 0x4}}}, ...)
        /home/runner/work/gov4git/gov4git/proto/ballot/ballot/vote.go:50 +0x348
github.com/gov4git/gov4git/proto/ballot/ballot.Vote({_, _}, {{{0xc00001e340, 0x37}, {0xc00000a684, 0x4}}, {{0xc00001e380, 0x38}, {0xc00000a688, 0x4}}}, ...)
        /home/runner/work/gov4git/gov4git/proto/ballot/ballot/vote.go:28 +0x205
github.com/gov4git/gov4git/gov4git/cmd.glob..func14(0xc000146f00?, {0x167228d?, 0x4?, 0x167218d?})
        /home/runner/work/gov4git/gov4git/gov4git/cmd/ballot.go:154 +0x133
github.com/spf13/cobra.(*Command).execute(0x1c72f20, {0xc0000a0090, 0x9, 0x9})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x863
github.com/spf13/cobra.(*Command).ExecuteC(0x1c70400)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/gov4git/gov4git/gov4git/cmd.Execute()
        /home/runner/work/gov4git/gov4git/gov4git/cmd/root.go:103 +0x1a
main.main.func1()
        /home/runner/work/gov4git/gov4git/gov4git/main.go:15 +0xf
github.com/gov4git/lib4git/must.TryWithStack(0x0?)
        /home/runner/go/pkg/mod/github.com/gov4git/lib4git@v0.0.27/must/must.go:64 +0x79
main.main()
        /home/runner/work/gov4git/gov4git/gov4git/main.go:14 +0x1e

file does not exist
```

Jason first discovered the problem and opened an issue here which has some extra logs: https://github.com/gov4git/desktop-application/issues/32

**Comment by petar** [comment]
@dworthen I discovered the cause of the issue. When Kasia was being issued credits using the lowercase username (rather than the correct camel case one), the system created this invalid folder in the users directory: https://github.com/pluralitybook/plurality-gov.public/tree/main/members/users/eviopfijucfpdgfahjtrvgonj43gssj4r2pklt5igkzc53liw5lq/wzpkjxmc3kqlff2wc3aobltsawyj24a2g5uctubtiid4afwitw5q

This is causing any operation that lists users to produce the error that you are observing. I can fix the issue by removing this invalid directory (and Kasia needs to be reissued credits). However I also need to understand why issuing credits to an incorrectly-cased username produced this odd directory.

**Comment by petar** [comment]
Steps to address this:
- [ ] desktop app should send only lowercase usernames to gov4git cli (@dworthen )
- [ ] all usernames ingested from GitHub should be converted to lowercase before using inside gov4git
- [ ] remove kasia's user manually (we need to rejoin her after the fix)
- [ ] remove the corrupt directory (mentioned above)
- [ ] understand why the corrupt directory was created

**Comment by dworthen** [comment]
@petar, That is strange. The logs show that the `group list --name everybody` is returning successfully with the follow results

```json
[
  "KasiaSun",
  "jason-entenmann",
  "dworthen",
  "petar",
  "giselechou"
]
```

**Comment by dworthen** [comment]
@petar The desktop app uses what is listed in the everybody group so for Kasia it sends `KasiaSun` to the cli for the appropriate commands. It has to use what the CLI has listed as the CLI seems to be case sensitive. As for the join request, I have no control over that since it is a GitHub issue and uses the listed GH username. It seems the CLI and cron job need to update to add users as all lowercase when responding to join requests.

**Comment by dworthen** [comment]
@petar Why is someone else's name interfering with my ability or Jason's ability to vote?

**Comment by petar** [comment]
@dworthen Jason cannot vote because the voting verification logic lists all users (qv/verify.go:26) to find if there is one matching the voter's (Jason's ID). And the listing process fails due to the corrupt directory present in the users subdirectory.

The real issue is why this corrupt directory was inserted there. And its related to Kasia. Kasia is the only user with camelcase username. So I suspect we'll have problems with everyone who has non-lowercase github username. So this is the key problem to resolve.

**Comment by dworthen** [comment]
Update @petar the `group list --name everybody` just started failing now.

**Comment by petar** [comment]
@dworthen I forgot to delete Kasia from group everybody as I was doing this manually. Should work now?

**Comment by dworthen** [comment]
@petar The user listing is working again and I am now getting a new error when voting `user with id ayaxgy3zspg34drfei7wttuxmxhbdpmiaacv2ra4lm25m6swk57a` cannot be found in the community. This might be because I jumped the gun in my testing and reset my identity repos and need to be readded to the community. Can you do that for me?

**Comment by dworthen** [comment]
@petar I removed and readded myself to the plurality community and was able to vote. My vote is pending and waiting on the cron job to be tallied.

**Comment by petar** [comment]
@dworthen Im going to push a fix which always converts usernames coming from github to lowercase. Make sure that in the desktop app, even if a user types in a non-lowercase username, you always treat it as lowercase everywhere. Incidentally, where do you use the username that users manually type in for themselves in the config screen of the app?

**Comment by dworthen** [comment]
@petar The username provided in the config is used to check if they are member of the everybody group in a case insensitive way but then uses the username as shown in the everybody group going forward. So if the cli/cron job insert users in lowercase that is what will be used throughout the app regardless of what they provide in the config and should work. I did it this way because at the time just simply converting to lowercase would cause issues if it did not exactly match the case as shown in the community.

**Comment by petar** [comment]
@dworthen Great! I just released https://github.com/gov4git/gov4git/releases/tag/v1.1.14 which fixes the lowercase issue, i.e. all users entering gov4git from GitHub will use their github usernames in lowercase inside to gov4git. This release also prohibits balance operations on non-existent users, which is what seems to have happened with Kasia's user when the corrupt directory appeared. This will prevent the corrupt directory problem from re-emerging, but I still want to understand why the corrupted directory was created. This is delegated to https://github.com/gov4git/gov4git/issues/126

Next steps:
- [x] @petar  will deploy https://github.com/gov4git/gov4git/releases/tag/v1.1.14 on plurality
- [ ] @dworthen will update the desktop app to use v1.1.14
- [ ] @KasiaSun's corrupt user was deleted, so she needs to re-join
