### ISSUE TITLE
I'd like to join this project's community

### ISSUE THREAD

**Issue by melscoop** [gov4git/gov4git#13]
### Your public repo

https://github.com/melscoop/gov4git.public

### Your public branch

main

### Your email (optional)

melscoop@github.com

**Comment by petar** [comment]
Hi @melscoop. Thanks for participating! I found a bug in the dogfood instructions while processing your request. 
Users must initialize their gov4git identity before they can join. I've updated the instructions by adding this section https://github.com/gov4git/gov4git/blob/main/doc/dogfood/how-to-join.md#quick-setup on getting yourself setup. Let me know if/when you can carry out the "quick setup" and then I will be able to add your user to the community. Thank you!
