### ISSUE TITLE
using the app with multiple user identities

### ISSUE THREAD

**Issue by petar** [gov4git/gov4git#130]
while operating and troubleshooting, we need a way to use the desktop app on behalf of different github users

related https://github.com/gov4git/desktop-application/issues/39

**Comment by dworthen** [comment]
@petar, The app allows users to log out to then select a different account to log in with. The app also lets users provide a custom PAT when deploying communities. Does this suffice? If not, what are we trying to achieve with multiple user accounts?

**Comment by petar** [comment]
@dworthen I think this should suffice for now. I needed this feature for debugging at some point, and what we have sounds sufficient. For the product, it is nice for users to be able to change identities, but it is not crucial that we have features like on Google Mail app where you can click between different identities. So we can close this issue for now.
