### ISSUE TITLE
ui: when desktop users use a GitHub token with insufficient privileges, the app silently proceeds without error

### ISSUE THREAD

**Issue by petar** [gov4git/gov4git#133]
when desktop users enter a personal GitHub token with insufficient privileges, usually because because they missed the instructions on the screen, the desktop app does not produce an error and moves on to the "request membership" screen.

it appears to create the user's public and private identity repos, but their contents is empty.

thanks @banklesschick for reporting

**Comment by dworthen** [comment]
I am unable to replicate this issue. When using an insufficient PAT token I tend to get the error message as documented in gov4git/desktop-application#39. In any case, gov4git/desktop-application#41 checks that the PAT token has sufficient privileges prior to logging in and presents a new message if it does not.

![image](https://github.com/gov4git/gov4git/assets/624870/d29b0ba8-f5a0-445f-a3aa-771f1db58c60)

@banklesschick , please open the app and let it update to latest version, 0.6.4, and let me know if you are still experiencing this issue.

**Comment by petar** [comment]
@dworthen The user may have created a fine-grain token (instead of a classic one). Maybe this helps reproduce it?

**Comment by dworthen** [comment]
This was resolved with the release of gov4git/desktop-application#64 since it now uses a device auth flow instead of requiring users to create and provide a PAT. The app is able to request the privileges it requires.
