### ISSUE TITLE
I'd like to join this project's community

### ISSUE THREAD

**Issue by tflaj** [gov4git/gov4git#15]
### Your public repo

https://github.com/tflaj/gov4git.public

### Your public branch

[main](https://github.com/tflaj/gov4git.public/branches)

### Your email (optional)

tflaj@github.com

**Comment by petar** [comment]
Hi @tflaj . Please initialize your identity before I can add you to the community. You can follow the instructions here https://github.com/gov4git/gov4git/blob/main/doc/dogfood/how-to-join.md#quick-setup

This step will generate public and private keys for your identity and will place your public keys in your public repo.
