### ISSUE TITLE
I'd like to join this project's community

### ISSUE THREAD

**Issue by shaudubey** [gov4git/gov4git#16]
### Your public repo

https://github.com/shaudubey/gov4git.public

### Your public branch

main

### Your email (optional)

dubeyshaurya@gmail.com

**Comment by petar** [comment]
Hi @shaudubey . You would have to initialize your identity first before I can add you as a member. Follow these instructions here https://github.com/gov4git/gov4git/blob/main/doc/dogfood/how-to-join.md#quick-setup Happy Holidays!

**Comment by shaudubey** [comment]
File was in the wrong path! I think it is initialized now. Happy Holidays.

**Comment by petar** [comment]
After you initialize your repo using `gov4git init-id` you should see a `public_credentials.json` file appear in your repository. Just like in this example: https://github.com/petar/gov4git.public/blob/main/id/public_credentials.json

**Comment by shaudubey** [comment]
I see those `json` files now, thank you!

**Comment by petar** [comment]
Great. I added you to the community. You can now proceed with https://github.com/gov4git/gov4git/blob/main/doc/dogfood/how-to-participate.md
