### ISSUE TITLE
Unable to Generate Public & Private Identity Keys for Repos 

### ISSUE THREAD

**Issue by the-kscar** [gov4git/gov4git#18]
**Describe the bug**
When I run `gov4git init-id`, I receive the following error `bcrypt_pbkdf: empty password`

What is the expected output to verify success?

**To Reproduce**
As instructed the following config file was used - 
```
{
     "auth" : {
          "git@github.com:petar/gov4git.public.git": {
               "ssh_private_keys_file": "/Users/my_username/.ssh/id_rsa"
          },
          "git@github.com:petar/gov4git.private.git": {
               "ssh_private_keys_file": "/Users/my_username/.ssh/id_rsa"
          }
     },
     "gov_public_url": "https://github.com/gov4git/governance.git",
	"gov_public_branch": "main",
	"member_public_url": "git@github.com:my_username/gov4git.public.git",
	"member_public_branch": "main",
	"member_private_url": "git@github.com:my_username/gov4git.private.git",
	"member_private_branch": "main"
}
```

This file is located in `~/.gov4git/config.json`

I also double checked the projects were writable. 

**Expected behavior**
A key generation file stored in the public and private repos identified. 

**Attach the logs**
No logs available.

**Comment by petar** [comment]
The auth section of your config seems incorrect. Maybe you pasted it from the doc and forgot to change it?

**Comment by the-kscar** [comment]
Thanks for getting back. It is updated with my correct username and path on my machine. (Tried to make the above generic.)

**Comment by petar** [comment]
Can you manually 'git clone' these repositories on your local machine using the same urls you have in the config and the same ssh credentials file?

**Comment by petar** [comment]
Also what operating system are you using?

**Comment by petar** [comment]
While the `ssh` method of authentication should work and I want to understand why it isn't in your case, I also want to let you know that you can access your repos using HTTPS instead, using a GitHub access token. Here is the respective config you can use:

```
{
     "auth" : {
          "https://github.com/my_username/gov4git.public.git": {
               "access_token": "YOUR_GITHUB_ACCESS_TOKEN"
          },
          "https://github.com/my_username/gov4git.private.git": {
               "access_token": "YOUR_GITHUB_ACCESS_TOKEN"
          }
     },
     "gov_public_url": "https://github.com/gov4git/governance.git",
	"gov_public_branch": "main",
	"member_public_url": "https://github.com/my_username/gov4git.public.git",
	"member_public_branch": "main",
	"member_private_url": "https://github.com/my_username/gov4git.private.git",
	"member_private_branch": "main"
}
```

You'll need to create a GitHub access token that has read/write access to these repositories.

**Comment by dworthen** [comment]
Hey @petar, I am having the same issue on Ubuntu through WSL. Here is my config: 

Note that I am setting up community and identity repos for testing purposes. 
```json
{
    "auth": {
        "git@github.com:dworthen/g4g-demo-community-public.git": {
            "ssh_private_keys_file": "PATH_TO_KEY"
        },
        "git@github.com:dworthen/g4g-demo-community-private.git": {
            "ssh_private_keys_file": "PATH_TO_KEY"
        },
        "git@github.com:dworthen/dworthen-g4g-public.git": {
            "ssh_private_keys_file": "PATH_TO_KEY"
        },
        "git@github.com:dworthen/dworthen-g4g-private.git": {
            "ssh_private_keys_file": "PATH_TO_KEY"
        }
    },
    "gov_public_url": "git@github.com:dworthen/g4g-demo-community-public.git",
    "gov_public_branch": "main",
    "gov_private_url": "git@github.com:dworthen/g4g-demo-community-private.git",
    "gov_private_branch": "main",
    "member_public_url": "git@github.com:dworthen/dworthen-g4g-public.git",
    "member_public_branch": "main",
    "member_private_url": "git@github.com:dworthen/dworthen-g4g-private.git",
    "member_private_branch": "main"
}
```

with this outcome using the --verbose flag:

```bash
> gov4git init-id --verbose
goroutine 1 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/gov4git/lib4git/must.mkErr(...)
        /home/dworthen/go/pkg/mod/github.com/gov4git/lib4git@v0.0.9/must/must.go:16
github.com/gov4git/lib4git/must.Panic(...)
        /home/dworthen/go/pkg/mod/github.com/gov4git/lib4git@v0.0.9/must/must.go:20
github.com/gov4git/lib4git/must.NoError(...)
        /home/dworthen/go/pkg/mod/github.com/gov4git/lib4git@v0.0.9/must/must.go:36
github.com/gov4git/lib4git/git.MakeSSHFileAuth({0xb71588, 0xc00018a180}, {0xa8cd98?, 0x14?}, {0xc00002a3e0?, 0x80efa8?})        /home/dworthen/go/pkg/mod/github.com/gov4git/lib4git@v0.0.9/git/auth.go:23 +0x78
github.com/gov4git/gov4git/gov4git/cmd.Config.Setup({0xc00018b920, {0xc0000326c0, 0x35}, {0xc000029170, 0x4}, {0xc000032700, 0x36}, {0xc000029174, 0x4}, {0xc00002d170, ...}, ...}, ...)
        /home/dworthen/go/pkg/mod/github.com/gov4git/gov4git@v1.0.3/gov4git/cmd/proto.go:56 +0x266
github.com/gov4git/gov4git/gov4git/cmd.initAfterFlags()
        /home/dworthen/go/pkg/mod/github.com/gov4git/gov4git@v1.0.3/gov4git/cmd/root.go:84 +0x3a5
github.com/spf13/cobra.(*Command).preRun(...)
        /home/dworthen/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:946
github.com/spf13/cobra.(*Command).execute(0xf1d6a0, {0xc0000fcfc0, 0x1, 0x1})
        /home/dworthen/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:876 +0x563
github.com/spf13/cobra.(*Command).ExecuteC(0xf1f360)
        /home/dworthen/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /home/dworthen/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/gov4git/gov4git/gov4git/cmd.Execute()
        /home/dworthen/go/pkg/mod/github.com/gov4git/gov4git@v1.0.3/gov4git/cmd/root.go:92 +0x25
main.main.func1()
        /home/dworthen/go/pkg/mod/github.com/gov4git/gov4git@v1.0.3/gov4git/main.go:14 +0x17
github.com/gov4git/lib4git/must.TryWithStack(0x405d3c?)
        /home/dworthen/go/pkg/mod/github.com/gov4git/lib4git@v0.0.9/must/must.go:57 +0x84
main.main()
        /home/dworthen/go/pkg/mod/github.com/gov4git/gov4git@v1.0.3/gov4git/main.go:13 +0x25

bcrypt_pbkdf: empty password
```

I am using ed25519 keys and noticed that the ID schema located in `proto/id/schema.go` might indicate support for ed25519 keys using 'private_key_ed25519' JSON keys so I also tried initializing with the following config:

```json
{
    "auth": {
        "git@github.com:dworthen/g4g-demo-community-public.git": {
            "private_key_ed25519": "/home/dworthen/.ssh/id_ed25519"
        },
        "git@github.com:dworthen/g4g-demo-community-private.git": {
            "private_key_ed25519": "/home/dworthen/.ssh/id_ed25519"
        },
        "git@github.com:dworthen/dworthen-g4g-public.git": {
            "private_key_ed25519": "/home/dworthen/.ssh/id_ed25519"
        },
        "git@github.com:dworthen/dworthen-g4g-private.git": {
            "private_key_ed25519": "/home/dworthen/.ssh/id_ed25519"
        }
    },
    "gov_public_url": "git@github.com:dworthen/g4g-demo-community-public.git",
    "gov_public_branch": "main",
    "gov_private_url": "git@github.com:dworthen/g4g-demo-community-private.git",
    "gov_private_branch": "main",
    "member_public_url": "git@github.com:dworthen/dworthen-g4g-public.git",
    "member_public_branch": "main",
    "member_private_url": "git@github.com:dworthen/dworthen-g4g-private.git",
    "member_private_branch": "main"
}
```

but running `gov4git init-id --verbose` hangs without any output. Looking out how the config is deserialized in `gov4git/cmd/proto.go` I am not sure the deserialization process accounts for ed25519 keys. Should those be supported at this time or is it expected to use rsa keys. I haven't tried that yet since the original post was using rsa keys and getting the same error.

**Comment by petar** [comment]
@dworthen The ssh keys are being read by the go-git library that we use (https://pkg.go.dev/github.com/go-git/go-git/v5/plumbing/transport/ssh#NewPublicKeys). It supports:

"PublicKeys from a PEM encoded private key. An encryption password should be given if the PEM bytes contain a password encrypted PEM block otherwise password should be empty. It supports RSA (PKCS#1), PKCS#8, DSA (OpenSSL), and ECDSA private keys."

So it looks like they don't support ed25519. (The reference to ed25519 that you saw in the code is not related to ssh authentication, it is part of gov4git's application-layer cryptography. Users prove their identities using ed25519 keys.)

I am wondering whether the message `bcrypt_pbkdf: empty password ` indicates that your PEM file requires a password (as hinted in the docstring above) . Does it?

**Comment by petar** [comment]
go-git uses golang.org/x/crypto/ssh to parse SSH PEM files. I discovered that the latest go-git (5.7.0) uses the latest golang.org/x/crypto/ssh, which supports more key types: It supports RSA, DSA, ECDSA, and Ed25519 private keys in PKCS#1, PKCS#8, OpenSSL, and OpenSSH formats.

Bumping the dependency should fix the problem with Ed25519 keys. I will plan to do this.

Still, we need to understand why the bcrypt password error.

**Comment by petar** [comment]
@dworthen I just pushed a new release https://github.com/gov4git/gov4git/releases/tag/v1.0.4 which uses the latest golang crypto library. Can you give it a try?

Does the bcrypt issue persists?
Are you able to use Ed25519 ssh keys?

**Comment by the-kscar** [comment]
> Can you manually 'git clone' these repositories on your local machine using the same urls you have in the config and the same ssh credentials file?

Yes, I double checked this.

**Comment by petar** [comment]
@the-kscar Please using gov4git again with your config. There is a new release which understands more SSH key file formats. The newest release is 1.0.4

**Comment by the-kscar** [comment]
Thanks @petar , I did try again on Windows 11. I also tried with the access token, to no avail. I was on an enterprise machine. Thought I might have better outcomes on a personal machine, which is running macOS 13.3.1. I'm having issues with installations the mac, I can see things downloaded, but I can't get gov4git to work...!

**Comment by petar** [comment]
@dworthen I am glad the access token way works. If your keys are password protected, then it is not going to work because in the current implementation I explicitly pass an empty password. I could add a "password" field to the config and thus support encrypted key files. I am not sure if this is a good practice though. Any thoughts?

**Comment by petar** [comment]
@the-kscar Are your SSH keys password protected?

**Comment by dworthen** [comment]
@petar, I think it would be ok if the cli tool supported env variables within the config file. 

```json
"access_token": "$ACCESS_TOKEN"
"ssh_password": "$GH_SSH_PASSWORD"
```

That way the access token, passwords and potentially other field values could be stored on the system through env variables and not placed directly in the config file. 

Though my preference for passwords would be for the tool to prompt for the password when needed. Is that possible?

**Comment by petar** [comment]
I think that when it comes to password entry, we should keep the standard behavior (of ssh) of querying the user for the password when the command is invoked. This is certainly doable, although it requires a little care to prevent repeated password prompts for the same password (like the ones you sometimes get when using package managers like `brew`).

I've created an issue to track this feature here https://github.com/gov4git/gov4git/issues/19.

I am assuming that @the-kscar is using a password-protected key file (based on the bcrypt error message), so this should resolve their problem as well. So, I am closing this issue as resolved (with the creation of https://github.com/gov4git/gov4git/issues/19).

**Comment by the-kscar** [comment]
Hi @petar , apologies for the time delay. In revisiting, I found some human errors in the original file I used for access tokens. I have since tried again and was able to generate my credentials. Thanks for all your help. I will look out for feature 19 as well.
