### ISSUE TITLE
I'd like to join this project's community

### ISSUE THREAD

**Issue by michelezanini** [gov4git/gov4git#195]
### Your public repo

https://github.com/michelezanini/gov4git-identity-public.git

### Your public branch

main

**Comment by GlenWeyl** [comment]
Did you intend to join this community or the book community, @michelezanini?

**Comment by michelezanini** [comment]
Hi Glen, I think I asked to join this after talking to Petar about Gov4Git.  Would I be in the right place?  I see you and Audrey are having a productive trip in Europe.  Safe travels!

Michele

**Comment by petar** [comment]
approve
