### ISSUE TITLE
System not approving new member

### ISSUE THREAD

**Issue by GlenWeyl** [gov4git/gov4git#199]
**Describe the bug**
In general, whenever a new member joins on the Plurality book and I approve it, they are immediately added.  However, a couple of days ago someone tried to join and I repeatedly approved it and they have not been added

**To Reproduce**
[Steps to reproduce the behavior](https://github.com/pluralitybook/plurality/issues/996)

**Expected behavior**
Should have approved membership

**Attach the logs**
Attach the logs from reproducing the bug using the verbose flag `-v`

**Comment by petar** [comment]
This is not a valid joint request. They didn't use the desktop app. There is no info describing the user's identity in this request.
