### ISSUE TITLE
ballot show-open not returning JSON

### ISSUE THREAD

**Issue by dworthen** [gov4git/gov4git#23]
Running `gov4git ballot show-open --name NAME` appears to be printing out a Go struct instead of JSON. 

![image](https://github.com/gov4git/gov4git/assets/624870/6f0d46da-fa3e-48e0-b8d2-4db94edf1308)

Can we update the command to return JSON to better support the Desktop client?

**Comment by petar** [comment]
@dworthen let me know if this fix works for you / looks good: https://github.com/gov4git/gov4git/pull/25

**Comment by petar** [comment]
Resolved by https://github.com/gov4git/gov4git/pull/25
