### ISSUE TITLE
ballance add behaves differently between Windows and *nix/Darwin platforms

### ISSUE THREAD

**Issue by dworthen** [gov4git/gov4git#24]
Running `gov4git balance add --user dworthen --key voting_credits ...` on Linux creates a file with a key `balance/voting_credits` while running the same command on Windows creates a file with a key of `balance\\voting_credits`.

Examples:
- File created when running on Linux: https://github.com/dworthen/g4g-demo-community-public/blob/main/members/users/se46kkxnb57mknhecuukfkslym5bfhu3dtpbzkiy4x6njyxhuuwa/wzpkjxmc3kqlff2wc3aobltsawyj24a2g5uctubtiid4afwitw5q/key.json
- File created when running on Windows: https://github.com/dworthen/g4g-demo-community-public/blob/main/members/users/se46kkxnb57mknhecuukfkslym5bfhu3dtpbzkiy4x6njyxhuuwa/fpmfzoulxmazmwr3sb4wd4b2qscdaovfavgmwz26zdwopdon3l5q/key.json

**Comment by petar** [comment]
Resolved by https://github.com/gov4git/gov4git/pull/27
