### ISSUE TITLE
automate provisioning of user repos on github

### ISSUE THREAD

**Issue by petar** [gov4git/gov4git#26]
add functionality: given the user's github credentials, provision a public and private repos for the user and initialize them with a new identity

**Comment by petar** [comment]
@dworthen Made this issue for tracking purposes.

**Comment by petar** [comment]
@dworthen I am looking into this. It looks like all I'll need to provision repos on behalf of the user is an access token. I am assuming we can help the user get an access token to github on the UI level: either using app authentication or any other methods?

**Comment by dworthen** [comment]
@petar, right now the UI is prompting users for a GitHub PAT token and then storing it in the `config.json` auth section as the associated `"access_token"` for the public and private identity repo urls upon intializing the config file. The UI is not supporting providing ssh keys and will always prompt for the PAT token. I am hoping the "access_token" is enough for initializing the repos.
