### ISSUE TITLE
Show command returns "file does not exist"

### ISSUE THREAD

**Issue by dworthen** [gov4git/gov4git#77]
**Describe the bug**

Running `gov4git ballot show --name issues/1` returns `file does not exist`. I can confirm that the ballot exists with `gov4git ballot list`. This command worked on previous versions of the CLI but is failing on 1.1.4. I tried updating the cache and it still fails. Running this on Windows.

**Comment by dworthen** [comment]
Looks like the command was failing with ballots opened from previous versions of the CLI as the path schemas have changed. I had to delete all the previous ballots to get the UI working again.

**Comment by petar** [comment]
Yep, indeed. The format changed. Eventually we should probably get serious about semver versioning, but prior to the mvp I'm not sure how to indicate breaking releases, so I just reflect it in the release notes.

**Comment by petar** [comment]
Come to look at it more closely, it wasn't very clearly stated in the release notes. I'll try to be better about this going forward.
