### ISSUE TITLE
Invalid credentials when voting

### ISSUE THREAD

**Issue by dworthen** [gov4git/gov4git#78]
**Describe the bug**

I am able to open new ballots as a community maintainer but I am unable to vote. Voting results in a "credentials are not valid" error.

```bash
g4g ballot vote --name issues/1 --choices Prioritize --strengths 4

credentials are not valid
```

I am using the same access_token and config files that worked with previous CLI versions and the access_token has not expired. I generated a new GH PAT just in case the old one was expired but that did not work. This started occurring after I updated to the v1.1.4 release on Windows.

**Comment by dworthen** [comment]
I was able to resolve this by completely deleting my community and id repos and starting over. I think there was just too much incompatibility between the old schemas and new ones.

**Comment by petar** [comment]
Yes, also caused by the protocol changes in v1.1.4.
