### ISSUE TITLE
ballot track returns "file does not exist" for ballots that have no votes

### ISSUE THREAD

**Issue by dworthen** [gov4git/gov4git#79]
**Describe the bug**

Tracking ballots returns "file does not exist" for ballots that exist but have no votes. 

```bash
g4g ballot track --name issues/1

file does not exist
```

**Comment by petar** [comment]
I would need the release number you are using. Current release going forward, the release version of your gov4git client is printed on the first line when using -v verbose mode.

This bug may be attributed to using an old ballot with a newer gov4git release that has the "track" functionality. Before "track" was supported, the ballot directory could be in a state without a tally file; this changed after "track" was added as tracking relies on always finding a tally file.

I'll close this for now, but feel free to reopen if the issue reoccurs with the current versions.
